Subscribe = "ベンソン級駆逐艦ラフィー、命令を待っている……"
Unsubscribe = "了解、命令されるまで寝る……"
NotSubscribed = "まだ通知が登録されてなかったよ……"
MarkAsRead = "既読にしておいた……"
BringIssue = "指揮官に、メール……"
BringPR = "コードレビュー終わったら、一緒にワイン飲もう……"
BringBranch = "指揮官も、気になる……？"
BringRepo = "頼まれた書類、持ってこれたよ……"
NothingToBring = "任務は無いみたい……"
EnumIssue = "まだ任務がありそう……"
EnumPR = "うん……そこそこ……？"
EnumBranch = "こんなの生えてたよ……"
InvalidToken = "トークンがおかしいみたい……"

Failure = [
  "ラフィー、よくわからない……",
  "今日、何かしないといけないこと……覚えていない……",
  "ラフィーは指揮官が悪いなんて思ってない。うん、思ってない…(ツンツン"
]

Flavor = [
  "Zzz……",
  "指揮官、疲れた？",
  "指揮官、よしよし……",
  "指揮官、一緒にねんねする？"
]

BlackPattern = "[精孕母乳味女こっぽんイコッポンｺｯﾎﾟﾝEHKTNehktn:○●_|\*]|はら|ハラ"
CallPattern = "ラフィ|らふぃ|laffey|Laffey"

HelpMessage = """```
/ghr (所属/)レポジトリ名 ==> リポジトリを持ってくる……
/ghb (所属/)レポジトリ名 ブランチ名 ==> ブランチを持ってくる……
/ghi (所属/)レポジトリ名(/数字) ==> Issue を持ってくる……
/ghp (所属/)レポジトリ名(/数字) ==> PR を持ってくる……

/ghs GitHubのID 通知トークン ==> GitHub 通知を DM にお届けする……
  通知トークンはこちらから作ってね……
  https://github.com/settings/tokens/new?scopes=repo&description=GitHub%20Secretary
/ghu ==> GitHub 通知を DM にお届けしなくなる……
/ghm 通知ID ==> GitHub 通知を既読にする……
  通知ID は、私が送ったメッセージに入ってる
  #012345678 の # 以降の数字部分だよ……
```"""
ErrorMessage = "そんなコマンド知らない…… `/gh?` でヘルプを見てみて……"
